Console.Clear();
Console.WriteLine ("Введите первое число");
int number1 = int.Parse(Console.ReadLine());
Console.WriteLine ("Введите второе число");
int number2 = int.Parse(Console.ReadLine());
//Console.WriteLine (number);
int square = number * number;
//Console.Write ("квадрат числа = ");
//Console.WriteLine ("квадрат числа" + number +"=" + square);
Console.WriteLine ($"квадрат числа {number} = {square}");
